name: plugin-kai
version: '1.0'
main: de.kaigoette.pluginKai.Main
api-version: '1.21'
commands:
  magic:
    description: Gives the player a Magic Stick
    usage: /magic
  resetscore:
    description: Resets the score of the player
    usage: /resetscore
  getExplosionBall:
    description: Gives the player an Explosion Ball
    usage: /getExplosionBall
  chatgpt:
    description: Chat with ChatGPT
    usage: /chatgpt <message>
  getWorldSwitcher:
    description: Gives the player a World Switcher
    usage: /getWorldSwitcher